== Education

[cols=2*,options="header", grid=none,frame=none]
|===
^| Student
^| Professor/Instructor

| *Master of Business Administration (MBA)* +
Fundação Getúlio Vargas São Paulo +
2010 - 2011 + 
https://educacao-executiva.fgv.br/
| *Graduate Studies Professor* + 
Senac São Paulo + 
2010 - 2011 + 
http://www.sp.senac.br

.2+| *Bachelor's in Computer and Information Sciences* +
Pontifícia Universidade Católica de São Paulo +
1999 - 2004 + 
https://www.pucsp.br/graduacao/ciencia-da-computacao
| *Java and Middleware Certified Instructor* +
Oracle Brazil + 
2008 - Present* + 
https://education.oracle.com/java/java/pFamily_48 + 
* _I'm living in Netherlands, back in Brazil I'm still an Oracle instructor_
 
| *Java/SAP ABAP Certified Instructor* +
SAP + 
2004 - 2008 +
https://www.impacta.com.br

|===

== Specializations

[cols=2*,options="header", grid=none,frame=none]
|===
^| Certifications
^| Courses

|*Certified Web Components for Java Platform +
Certified Programmer for Java Platform +
Certified Associate for Java Platform*

_Oracle (former Sun) University, 2006_
|*Hadoop Operations: Hadoop Administration Foundation*

_Hortonworks/Teradata, 2018_

.5+|*SAP Certified Instructor for SAP Technologies +
SAP Netweaver Workbench for ABAP*

_SAP University and Instructors Program, 2008_
| *MongoDB Aggregation Framework (M121)* +
*MongoDB for DBAs (M102)* +
*MongoDB for Java Developers (M101J)*

_Mongo University, 2016_


|*COBIT - Auditing IT Systems*

_Galegale & Associates, 2011_


|*ReST from Scratch +
Continuous Delivery (by Martin Fowler and Jez Humble)*

_QCon Conference Workshops, 2010_


|*Web Application Security Training*

_Bonsai Information Security, 2010_


|*Introduction to TCP/IP Architecture*

_Telefonica Brazil, 2006_

|===
