=== Nextel Telecommunications Brazil - http://nextel.com.br
.Billing Department System's Architect, November 2006 - July 2010 (3 years 9 months), São Paulo Area, Brazil

I had an impactful presence in Next Billing department, being responsible for the development of many important applications that contributed to significant improvements in the company's billing department.
Key achievements:

— Started to make use of maven build tool which was adopted by the department.
- Adopted test driven development using JUnit and shared this knowledge with the team.
- Created a SOA infrastructure for applications that I was responsible for and over time this architecture was adopted by members of the department.
- Leading by example, I was able to show the benefits of using the best practices of development and the importance of using the best tools for the job.

Also, I had an opportunity to work close with the BSCS Billing System, which allowed me to learn a lot about the system and how to integrate with it and manage its main services, such as billing, rating, mediation, provisioning, etc.

include::nextel_projects.adoc[]