=== TAUS - https://taus.net
.Chief Technology Officer, March 2020 - Present, Amsterdam, The Netherlands

At TAUS, I’m in charge of the whole engineering and data teams, I oversee everything that is created and align our technologies with the business goals. But what this really means is that I’m one of the actual doers, I don’t just communicate and explain the need but I also design and help to shape how it will look like technically speaking, a very hands-on position and attitude. I’m responsible for designing and implementing most of our core Data Architecture entirely based on serverless pipelines. I’m the head of a multidisciplinary and multipolyglot teams made of back and front enders and NLP research and analysts, working in different fronts that come together delivering production-ready products.
I led several projects, including the creation of a new data pipeline for our core data, complete digital transformation by deploying a set a new tools and processes, and recently the creation of a new product for the translation industry, TAUS Quality Estimate API. Some of these projects I helped to design and implement myself, others I led the team that did it, and others I was the one that made sure that the project was delivered on time and with the expected quality.
