=== TAUS - https://taus.net
.Head of Data & Engineering, March 2020 - Present, Amsterdam, The Netherlands

At TAUS, a data company where the main asset is translation data, we have over 35 billion words in several languages and we have platforms that enable translators to produce translation data - https://hlp.taus.net - or sell the translation data - https://datamarketplace.taus.net - they own. We apply NLP technology on all our data to ensure that it’s clean, reliable and ready for Machine Learning Translation and for that we have a robust data pipeline made of several components that ensure the high quality of our data. Also on our business pipeline is planned expansion our data offering for other kinds like annotated data, sounds, voices and more. At TAUS **I’m in charge of the whole engineering and data teams**, I oversee everything that is created and align our technologies with the business goals but that this really means is that I’m one of actual doers, I don’t just communicate and explain the need but I also design and help to shape how it will look like technically speaking, a very hands on position and attitude. I'm responsible design and implement most of our core Data Architecture entirely based on server less pipelines. I'm the head of a multidisciplinary and multipolyglot teams made of back and front enders and NLP research and analysts, working in different fronts that come together develivering production-ready products.
